services:
  shiptor_fias.service.fias:
    class: Shiptor\Bundle\FiasBundle\Service\FiasService
    arguments: [ "@service_container" ]
  # Http + Rpc Client
  guzzle.client:
      class: GuzzleHttp\Client
  rpc_client.protocol.jsonrpc:
      class: Moriony\RpcClient\Protocol\JsonRpcProtocol
  rpc_client.transport.guzzle:
      class: Moriony\RpcClient\Transport\GuzzleTransport
      arguments: [ "@guzzle.client" ]
  rpc_client.client:
      class: Moriony\RpcClient\Client
      arguments:
          -
              protocols:
                  jsonrpc: "@rpc_client.protocol.jsonrpc"
              transport: "@rpc_client.transport.guzzle"
